negative test
Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

diff --git a/.github/workflows/attest-build-provenance-slsa3-rw.yml b/.github/workflows/attest-build-provenance-slsa3-rw.yml
--- a/.github/workflows/attest-build-provenance-slsa3-rw.yml
+++ b/.github/workflows/attest-build-provenance-slsa3-rw.yml
@@ -66,8 +66,8 @@ jobs:
     runs-on: ${{ inputs.build-runner-label }}
     steps:
       - name: detect-runner
-        if: ${{ runner.environment == 'github-hosted' }}
-        run: echo "github-hosted runner detected"
+        if: ${{ runner.environment != 'github-hosted' }}
+        run: echo "self-hosted runner detected, failing job!" && exit 1
       - name: checkout-source-repo
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
       - name: slsa-build
@@ -89,8 +89,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: detect-runner
-        if: ${{ runner.environment == 'github-hosted' }}
-        run: echo "github-hosted runner detected"
+        if: ${{ runner.environment != 'github-hosted' }}
+        run: echo "self-hosted runner detected, failing job!" && exit 1
       - name: download-artifact
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
         with:
@@ -128,8 +128,8 @@ jobs:
         # ^https://github.com/ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@v[0-9].[0-9].[0-9]$
     steps:
       - name: detect-runner
-        if: ${{ runner.environment == 'github-hosted' }}
-        run: echo "github-hosted runner detected"
+        if: ${{ runner.environment != 'github-hosted' }}
+        run: echo "self-hosted runner detected, failing job!" && exit 1
       - name: download-artifact
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
         with:
