self-hosted runner check
Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

diff --git a/.github/workflows/attest-build-provenance-slsa3-rw.yml b/.github/workflows/attest-build-provenance-slsa3-rw.yml
--- a/.github/workflows/attest-build-provenance-slsa3-rw.yml
+++ b/.github/workflows/attest-build-provenance-slsa3-rw.yml
@@ -53,16 +53,18 @@ on:
         default: ${{ github.token }}
         required: false
         type: string
-      runner-label:
-        default: ubuntu-latest
-        required: false
+      build-runner-label:
+        description: >
+          The runner label to pass to `runs-on:`. e.g., "ubuntu-latest". 
+        required: true
         type: string
 
 jobs:
-  build:
+  slsa3-build:
     permissions:
       contents: read
-    runs-on: ubuntu-latest
+    runs-on: ${{ inputs.build-runner-label }}`
+    
     steps:
       - name: checkout-source-repo
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
@@ -78,12 +80,32 @@ jobs:
           if-no-files-found: error
 
   attest:
-    needs: build
+    needs: slsa3-build
     permissions:
       id-token: write
       attestations: write
-    runs-on: ${{ inputs.runner-label }}
+    runs-on: ubuntu-latest
     steps:
+      - name: build-runner-check
+        id: build-runner-check
+        env:
+          RUN_ID: $${}
+          RUN_ATTEMPT:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+            # get the job id number of `slsa3-build`. Then get the logs of the "Set up job" activity.
+            # these logs contain markers that identity use of self-hosted runners.
+            # "Machine name:" should only appear in the logs for self-hosted runners.
+            # See https://github.com/actions/runner/pull/539/files#diff-e10dd2daf26c47f8e2914b189bbbc8043bdcd073c633c9a2d29d67f0ec3b4581R77. 
+            JOB_ID=$( gh run view "$RUN_ID" --attempt "$RUN_ATTEMPT" --json jobs | jq '.jobs[] | select(.name|endswith("/ slsa3-build")) | .databaseId' )
+            JOB_LOGS=$( gh run view "$RUN_ID" --job "$JOB_ID" --log | sed -n -e '/Set up job/I,/Complete job name/I p' )
+            if grep -qi "Machine name:" <<< $JOB_LOGS; then
+                echo "detected a self-hosted runner, aborting attestation!"
+                exit 1
+            else
+                echo "self-hosted runner not detected."
+                exit 0
+            fi
       - name: download-artifact
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
         with:
