second method
Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

diff --git a/.github/workflows/attest-build-provenance-slsa3-rw.yml b/.github/workflows/attest-build-provenance-slsa3-rw.yml
--- a/.github/workflows/attest-build-provenance-slsa3-rw.yml
+++ b/.github/workflows/attest-build-provenance-slsa3-rw.yml
@@ -71,6 +71,7 @@ jobs:
       - name: checkout-source-repo
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
       - name: slsa-build
+        if: ${{ runner.environment == 'github-hosted' }}
         uses: ./.github/actions/slsa-build
         env:
           GITHUB_TOKEN: ${{ inputs.subject-path }}
@@ -91,11 +92,33 @@ jobs:
       - name: detect-runner
         if: ${{ runner.environment != 'github-hosted' }}
         run: echo "self-hosted runner detected, failing job!" && exit 1
+      - name: build-detect-check
+        # Get the job id number of `slsa3-build`. Then get the logs of the "Set up job" activity.
+        # these logs contain markers that identity use of self-hosted runners.
+        # "Machine name:" should only appear in the logs for self-hosted runners.
+        # See
+        # - https://github.com/actions/runner/pull/539/files#diff-e10dd2daf26c47f8e2914b189bbbc8043bdcd073c633c9a2d29d67f0ec3b4581R77
+        # - https://github.com/orgs/community/discussions/111347#discussioncomment-10490619
+        env:
+          RUN_ID: $${}
+          RUN_ATTEMPT:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+            JOB_ID=$( gh run view "$RUN_ID" --attempt "$RUN_ATTEMPT" --json jobs | jq '.jobs[] | select(.name|endswith("/ slsa3-build")) | .databaseId' )
+            JOB_LOGS=$( gh run view "$RUN_ID" --job "$JOB_ID" --log | sed -n -e '/Set up job/I,/Complete job name/I p' )
+            if grep -qi "Machine name:" <<< $JOB_LOGS; then
+                echo "detected a self-hosted runner, aborting attestation!"
+                exit 1
+            else
+                echo "self-hosted runner not detected."
+                exit 0
+            fi
       - name: download-artifact
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
         with:
           name: ${{ inputs.build-artifact-name }}
       - name: attest-build-provenance
+        if: ${{ runner.environment == 'github-hosted' }}
         id: attest-build-provenance
         uses: actions/attest-build-provenance@310b0a4a3b0b78ef57ecda988ee04b132db73ef8 # v1.4.1
         with:
