more complete draft, debug log checker
Signed-off-by: Ramon Petgrave <ramon.petgrave64@gmail.com>

diff --git a/.github/workflows/attest-build-provenance-slsa3-rw.yml b/.github/workflows/attest-build-provenance-slsa3-rw.yml
--- a/.github/workflows/attest-build-provenance-slsa3-rw.yml
+++ b/.github/workflows/attest-build-provenance-slsa3-rw.yml
@@ -10,6 +10,7 @@
 #       contents: read
 #     uses: ramonpetgrave/github-build-attestations-rw/.github/workflows/attest-build-provenance-slsa3-rw.yml@dev
 #     with:
+#       build-runner-label: ubuntu-latest
 #       subject-path: |
 #         ./gundam
 #         ./myhero
@@ -47,7 +48,7 @@ on:
         default: true
         required: false
         type: boolean
-      github-token:
+      build-github-token:
         description: >
           The GitHub token used as environment variable GH_TOKEN to ./slsa_build.sh.
         default: ${{ github.token }}
@@ -60,7 +61,7 @@ on:
         type: string
 
 jobs:
-  build:
+  run-slsa-build-action:
     outputs:
       job-id: ${{ github.job }}
     permissions:
@@ -76,7 +77,7 @@ jobs:
         if: ${{ runner.environment == 'github-hosted' }}
         uses: ./.github/actions/slsa-build
         env:
-          GITHUB_TOKEN: ${{ inputs.subject-path }}
+          GITHUB_TOKEN: ${{ inputs.build-github-token }}
       - name: upload-artifact
         uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a #v4.3.6
         with:
@@ -84,8 +85,8 @@ jobs:
           path: ${{ inputs.subject-path }}
           if-no-files-found: error
 
-  attest:
-    needs: build
+  attest-build-artifacts:
+    needs: run-slsa-build-action
     permissions:
       id-token: write
       attestations: write
@@ -98,29 +99,44 @@ jobs:
       - name: detect-runner
         if: ${{ runner.environment != 'github-hosted' }}
         run: echo "self-hosted runner detected, failing job!" && exit 1
-      - name: build-detect-check
-        # Get the job id number of `slsa3-build`. Then get the logs of the "Set up job" activity.
+      - name: detect-build-job-runner
+        # Get the job id number of `run-slsa-build-action`. Then get the logs of the "Set up job" activity.
         # these logs contain markers that identity use of self-hosted runners.
         # "Machine name:" should only appear in the logs for self-hosted runners.
         # See
         # - https://github.com/actions/runner/pull/539/files#diff-e10dd2daf26c47f8e2914b189bbbc8043bdcd073c633c9a2d29d67f0ec3b4581R77
         # - https://github.com/orgs/community/discussions/111347#discussioncomment-10490619
+        # Since there may be multiple Jobs named `run-slsa-build-action`, and our Job name is particular, we retrieve the logs for all 
+        # Jobs with that name.
         env:
           WORKFLOW_NAME: 
           RUN_ID: ${}
-          BUILD_JOB_ID: ${{ needs.build.outputs.job-id }}
+          BUILD_JOB_ID: ${{ needs.run-slsa-build-action.outputs.job-id }}
           RUN_ATTEMPT: ${{ github.run_attempt }}
           GH_TOKEN: ${{ github.token }}
         run: |
-            # $BUILD_JOB_ID=$( gh run view "$RUN_ID" --attempt "$RUN_ATTEMPT" --json jobs | jq '.jobs[] | select(.name|endswith("/ build")) | .databaseId' )
-            JOB_LOGS=$( gh run view "$RUN_ID" --job "$BUILD_JOB_ID" --log | sed -n -e '/Set up job/I,/Complete job name/I p' )
-            if grep -qi "Machine name:" <<< $JOB_LOGS; then
-                echo "detected a self-hosted runner, aborting attestation!"
-                exit 1
-            else
-                echo "self-hosted runner not detected."
-                exit 0
-            fi
+          BUILD_JOB_IDS=$(
+            gh run view "$RUN_ID" --attempt "$RUN_ATTEMPT" --json jobs \
+                --jq '.jobs[] | select((.conclusion="success") and (.name | endswith("run-slsa-build-action"))) | .databaseId'
+          )
+          while read -r ID; do
+              echo getting "Set up job" logs for Job "$ID"
+              JOB_LOGS=$( gh run view "$RUN_ID" --job "$ID" --log | sed -n -e '/Set up job/I,/Complete job name/I p' )
+              ABORT=false
+              if grep -qi "Machine name:" <<< "$JOB_LOGS"; then
+                  echo "detected a self-hosted runner, aborting attestation!"
+                  ABORT=true
+              else
+                  echo "self-hosted runner not detected."
+              fi
+          done <<< "$BUILD_JOB_IDS"
+          if [ "$ABORT" = true ]; then
+              echo "Detected self hosted runner. Aborting"
+              exit 1
+          else
+              echo "No self hosted runner detected. Proceeding."
+              exit 0
+          fi
       - name: download-artifact
         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
         with:
@@ -140,7 +156,7 @@ jobs:
           if-no-files-found: error
 
   verify:
-    needs: attest
+    needs: attest-build-artifacts
     runs-on: ubuntu-latest
     env:
       GH_TOKEN: ${{ github.token }}
@@ -172,7 +188,7 @@ jobs:
           name: ${{ inputs.build-attestation-name }}
       - name: ls
         run: ls -lahR
-      - name: online-with-cert-identity
+      - name: online-verify-with-cert-identity
         run: |
           for FILE in "$ARTIFACTS_FOLDER"/*; do
             gh attestation verify \
@@ -180,28 +196,4 @@ jobs:
               --deny-self-hosted-runners \
               --repo "$REPO" \
               --cert-identity "$CERT_IDENTITY"
-          done
-      # see https://github.com/cli/cli/issues/9521
-      - name: fix-local-attestation-bundle
-        run: truncate -s -1 "$LOCAL_ATTESTATION_FILEPATH"
-      - name: offline-local-attestation-with-cert-identity
-        run: |
-          for FILE in "$ARTIFACTS_FOLDER"/*; do
-            gh attestation verify \
-              $FILE \
-              --deny-self-hosted-runners \
-              --repo "$REPO" \
-              --cert-identity "$CERT_IDENTITY" \
-              --bundle "$LOCAL_ATTESTATION_FILEPATH"
-          done
-      - name: offline-downloaded-attestation-with-cert-identity-with-branch-main
-        run: |
-          for FILE in "$ARTIFACTS_FOLDER"/*; do
-            gh attestation verify \
-              $FILE \
-              --deny-self-hosted-runners \
-              --repo "$REPO" \
-              --cert-identity "$CERT_IDENTITY" \
-              --bundle "$LOCAL_ATTESTATION_FILEPATH" \
-            | jq --exit-status '.[].verificationResult.signature.certificate.sourceRepositoryRef | select(.=="refs/heads/main")'
           done
